wip postgres fix
Signed-off-by: Danny Berger <dberger@pivotal.io>

diff --git a/jobs/postgres-9.4/templates/postgres.erb b/jobs/postgres-9.4/templates/postgres.erb
--- a/jobs/postgres-9.4/templates/postgres.erb
+++ b/jobs/postgres-9.4/templates/postgres.erb
@@ -51,5 +51,32 @@ $JOB_DIR/bin/postgres_db_backup.sh
 
 cp $JOB_DIR/config/postgresql.conf $DATA_DIR
 
+(
+  # wait for database to be running
+  for i in $( seq 0 30 ); do
+    if /var/vcap/packages/postgres-9.4/bin/oid2name -d postgres -q ; then
+      break
+    fi
+
+    sleep 1
+  done
+
+  set +e
+
+  for DBNAME in "${DBNAMES[@]}"; do
+    echo "Trying to create database $DBNAME..."
+    $PACKAGE_DIR/bin/createdb $DBNAME -h $HOST -p $PORT -U vcap
+    if [ $? != 0 ]; then
+      echo "Warning: failed to create $DBNAME; ignoring"
+    fi
+
+    echo "Trying to create user..."
+    $PACKAGE_DIR/bin/psql -d $DBNAME -h $HOST -p $PORT -U vcap -c "create role \"$USER\" NOSUPERUSER LOGIN INHERIT CREATEDB"
+
+    echo "Trying to alter user (to change password)..."
+    $PACKAGE_DIR/bin/psql -d $DBNAME -h $HOST  -p $PORT -U vcap -c "alter role \"$USER\" with password '$PASSWORD'"
+  done
+) &
+
 echo "Starting PostgreSQL:"
-$PACKAGE_DIR/bin/postgres -h $HOST -p $PORT -D $DATA_DIR
+exec $PACKAGE_DIR/bin/postgres -h $HOST -p $PORT -D $DATA_DIR
